let data={
	maxId:2,
	'0':{
		path:'data_0',
		name:'全部',
		pic:'img/cobo-quabb.png',
		picnew:'img/cobo-quabb2.png',
		child:{
			maxId:5,
			'0':{
				path:'data_0_child_0',
				name:'文档',
				pic:'img/cobo-wend.png',
				picnew:'img/cobo-wend2.png',
				child:{
					maxId:2,
					'0':{
						path:'data_0_child_0_child_0',
						name:'笔记本',
						child:{
							maxId:2,
							'0':{
								path:'data_0_child_0_child_0_child_0',
								name:'2017年笔记',
								child:{
									maxId:0
								}
							},
							'1':{
								path:'data_0_child_0_child_0_child_1',
								name:'2016年笔记',
								child:{
									maxId:0
								}
							}
						}
					},
					'1':{
						path:'data_0_child_0_child_1',
						name:'学习文档',
						child:{
							maxId:0
						}
					}
				}
			},
			'1':{
				path:'data_0_child_1',
				name:'图片',
				pic:'img/cobo-pic.png',
				picnew:'img/cobo-pic2.png',				
				child:{
					maxId:2,
					'0':{
						path:'data_0_child_1_child_0',
						name:'游学照',
						child:{
							maxId:0
						}
					},
					'1':{
						path:'data_0_child_1_child_1',
						name:'旅游照',
						child:{
							maxId:0
						}
					}
				}
			},
			'2':{
				path:'data_0_child_2',
				name:'视频',
				pic:'img/cobo-ship.png',
				picnew:'img/cobo-ship2.png',					
				child:{
					maxId:2,
					'0':{
						path:'data_0_child_2_child_0',
						name:'视频记录1',
						child:{
							maxId:0
						}
					},
					'1':{
						path:'data_0_child_2_child_1',
						name:'视频记录2',
						child:{
							maxId:0
						}
					}
				}
			},
			'3':{
				path:'data_0_child_3',
				name:'笔记',
				pic:'img/cobo-bij.png',
				picnew:'img/cobo-bij2.png',				
				child:{
					maxId:2,
					'0':{
						path:'data_0_child_3_child_0',
						name:'学习笔记',
						child:{
							maxId:0
						}
					},
					'1':{
						path:'data_0_child_3_child_1',
						name:'游记',
						child:{
							maxId:0
						}
					}
				}
			},
			'4':{
				path:'data_0_child_4',
				name:'音乐',
				pic:'img/cobo-yiny.png',
				picnew:'img/cobo-yiny2.png',					
				child:{
					maxId:2,
					'0':{
						path:'data_0_child_4_child_0',
						name:'欧美',
						child:{
							maxId:0
						}
					},
					'1':{
						path:'data_0_child_4_child_1',
						name:'RAP',
						child:{
							maxId:0
						}
					}
				}
			}
		}
	},
	'1':{
		path:'data_1',
		name:'垃圾箱',
		pic:'img/cobo-laji.png',
		picnew:'img/cobo-laji2.png',
		child:{
			maxId:0
		}
	}
};